---
name: Build project
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "src/**"
      - "test-page/**"
      - "build.gradle"
      - "gradle.properties"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Validate
        uses: pre-commit/action@v3.0.0

      - uses: docker/setup-buildx-action@v3

      - name: Install playwright
        run: npx playwright install-deps

      - name: Build and Run Test Page
        run: |
          docker compose build
          docker compose up -d --wait

      - name: Build and Test
        run: ./gradlew clean build

      - name: Upload coverage to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v
